# ==============================================================================
# Merged Lakeflow Source: dicomweb
# ==============================================================================
# This file is auto-generated by tools/scripts/merge_python_source.py
# Do not edit manually. Make changes to the source files instead.
# ==============================================================================

import json
import logging
import pathlib
import time
from abc import ABC, abstractmethod
from dataclasses import dataclass
from datetime import date, datetime, timedelta, timezone
from decimal import Decimal
from typing import Any, Iterator

import requests
from pyspark.sql import Row
from pyspark.sql.datasource import (
    DataSource,
    DataSourceReader,
    DataSourceStreamReader,
    InputPartition,
    SimpleDataSourceStreamReader,
)
from pyspark.sql.types import (
    ArrayType,
    BinaryType,
    BooleanType,
    ByteType,
    DataType,
    DateType,
    DecimalType,
    DoubleType,
    FloatType,
    IntegerType,
    LongType,
    MapType,
    ShortType,
    StringType,
    StructField,
    StructType,
    TimestampType,
    VariantType,
    VariantVal,
)
from requests.auth import HTTPBasicAuth


def register_lakeflow_source(spark):
    """Register the DICOMweb Lakeflow Python source with Spark."""

    ########################################################
    # src/databricks/labs/community_connector/libs/utils.py
    ########################################################

    def _parse_struct(value: Any, field_type: StructType) -> Row:
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for StructType, got {type(value)}")
        if value == {}:
            raise ValueError(
                "field in StructType cannot be an empty dict. Please assign None as the default value instead."
            )
        field_dict = {}
        for field in field_type.fields:
            if field.name in value:
                field_dict[field.name] = parse_value(value.get(field.name), field.dataType)
            elif field.nullable:
                field_dict[field.name] = None
            else:
                raise ValueError(f"Field {field.name} is not nullable but not found in the input")
        return Row(**field_dict)

    def _parse_array(value: Any, field_type: ArrayType) -> list:
        if not isinstance(value, list):
            if field_type.containsNull:
                return [parse_value(value, field_type.elementType)]
            raise ValueError(f"Expected a list for ArrayType, got {type(value)}")
        return [parse_value(v, field_type.elementType) for v in value]

    def _parse_map(value: Any, field_type: MapType) -> dict:
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for MapType, got {type(value)}")
        return {parse_value(k, field_type.keyType): parse_value(v, field_type.valueType) for k, v in value.items()}

    def _parse_string(value: Any) -> str:
        return str(value)

    def _parse_integer(value: Any) -> int:
        if isinstance(value, str) and value.strip():
            return int(float(value)) if "." in value else int(value)
        if isinstance(value, (int, float)):
            return int(value)
        raise ValueError(f"Cannot convert {value} to integer")

    def _parse_float(value: Any) -> float:
        return float(value)

    def _parse_decimal(value: Any) -> Decimal:
        return Decimal(value) if isinstance(value, str) and value.strip() else Decimal(str(value))

    def _parse_boolean(value: Any) -> bool:
        if isinstance(value, str):
            lowered = value.lower()
            if lowered in ("true", "t", "yes", "y", "1"):
                return True
            if lowered in ("false", "f", "no", "n", "0"):
                return False
        return bool(value)

    def _parse_binary(value: Any) -> bytes:
        if isinstance(value, bytes):
            return value
        if isinstance(value, bytearray):
            return bytes(value)
        if isinstance(value, str):
            import base64

            try:
                return base64.b64decode(value)
            except Exception:
                return value.encode("utf-8")
        return str(value).encode("utf-8")

    _PRIMITIVE_PARSERS = {
        StringType: _parse_string,
        IntegerType: _parse_integer,
        LongType: _parse_integer,
        ShortType: _parse_integer,
        ByteType: _parse_integer,
        FloatType: _parse_float,
        DoubleType: _parse_float,
        DecimalType: _parse_decimal,
        BooleanType: _parse_boolean,
        BinaryType: _parse_binary,
    }

    def parse_value(value: Any, field_type: DataType) -> Any:
        if value is None:
            return None
        if isinstance(field_type, StructType):
            return _parse_struct(value, field_type)
        if isinstance(field_type, ArrayType):
            return _parse_array(value, field_type)
        if isinstance(field_type, MapType):
            return _parse_map(value, field_type)
        if isinstance(field_type, VariantType):
            if isinstance(value, str):
                return VariantVal.parseJson(value)
            return value  # already a VariantVal
        field_type_class = type(field_type)
        if field_type_class in _PRIMITIVE_PARSERS:
            return _PRIMITIVE_PARSERS[field_type_class](value)
        return value

    ########################################################
    # src/databricks/labs/community_connector/interface/lakeflow_connect.py
    ########################################################

    class LakeflowConnect(ABC):
        def __init__(self, options: dict[str, str]) -> None:
            self.options = options

        @abstractmethod
        def list_tables(self) -> list[str]: ...

        @abstractmethod
        def get_table_schema(self, table_name: str, table_options: dict[str, str]) -> StructType: ...

        @abstractmethod
        def read_table_metadata(self, table_name: str, table_options: dict[str, str]) -> dict: ...

        @abstractmethod
        def read_table(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]: ...

        def read_table_deletes(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            raise NotImplementedError

    ########################################################
    # sources/dicomweb/dicomweb_parser.py
    ########################################################

    STUDY_TAG_MAP = {
        "0020000D": "StudyInstanceUID",
        "00080020": "StudyDate",
        "00080030": "StudyTime",
        "00080050": "AccessionNumber",
        "00100010": "PatientName",
        "00100020": "PatientID",
        "00081030": "StudyDescription",
        "00080061": "ModalitiesInStudy",
        "00201206": "NumberOfStudyRelatedSeries",
        "00201208": "NumberOfStudyRelatedInstances",
    }

    SERIES_TAG_MAP = {
        "0020000E": "SeriesInstanceUID",
        "0020000D": "StudyInstanceUID",
        "00080020": "StudyDate",
        "00200011": "SeriesNumber",
        "0008103E": "SeriesDescription",
        "00080060": "Modality",
        "00180015": "BodyPartExamined",
        "00080021": "SeriesDate",
    }

    INSTANCE_TAG_MAP = {
        "00080018": "SOPInstanceUID",
        "0020000E": "SeriesInstanceUID",
        "0020000D": "StudyInstanceUID",
        "00080016": "SOPClassUID",
        "00200013": "InstanceNumber",
        "00080020": "StudyDate",
        "00080023": "ContentDate",
        "00080033": "ContentTime",
    }

    _STRING_VRS = {"DA", "TM", "CS", "LO", "UI", "SH", "LT", "ST", "UT", "AE", "AS", "DT", "UC", "UR"}
    _NUMERIC_VRS = {"IS", "DS", "FL", "FD", "SL", "SS", "UL", "US"}

    def _extract_dicom_value(tag_obj: dict, field_name: str) -> object:
        vr = tag_obj.get("vr", "")
        values = tag_obj.get("Value", [])
        if not values:
            return None
        if vr == "PN":
            first = values[0]
            if isinstance(first, dict):
                return first.get("Alphabetic") or first.get("Ideographic") or first.get("Phonetic")
            return str(first)
        if vr in _STRING_VRS:
            if field_name == "ModalitiesInStudy":
                return [str(v) for v in values]
            return str(values[0])
        if vr in _NUMERIC_VRS:
            first = values[0]
            try:
                return int(first) if vr in {"IS", "US", "UL", "SS", "SL"} else float(first)
            except (TypeError, ValueError):
                return None
        first = values[0]
        return first if isinstance(first, (str, int, float, bool)) else str(first)

    def _parse_dicom_json(dicom_obj: dict, tag_map: dict) -> dict:
        result = {}
        for tag, field_name in tag_map.items():
            tag_obj = dicom_obj.get(tag.upper()) or dicom_obj.get(tag.lower())
            result[field_name] = _extract_dicom_value(tag_obj, field_name) if tag_obj else None
        return result

    def _parse_study(dicom_obj: dict) -> dict:
        return _parse_dicom_json(dicom_obj, STUDY_TAG_MAP)

    def _parse_series(dicom_obj: dict) -> dict:
        return _parse_dicom_json(dicom_obj, SERIES_TAG_MAP)

    def _parse_instance(dicom_obj: dict) -> dict:
        record = _parse_dicom_json(dicom_obj, INSTANCE_TAG_MAP)
        record.setdefault("dicom_file_path", None)
        record.setdefault("metadata", None)
        return record

    ########################################################
    # sources/dicomweb/dicomweb_schemas.py
    ########################################################

    STUDIES_SCHEMA = StructType(
        [
            StructField("StudyInstanceUID", StringType(), nullable=False),
            StructField("PatientID", StringType(), nullable=True),
            StructField("PatientName", StringType(), nullable=True),
            StructField("StudyDate", StringType(), nullable=True),
            StructField("StudyTime", StringType(), nullable=True),
            StructField("AccessionNumber", StringType(), nullable=True),
            StructField("StudyDescription", StringType(), nullable=True),
            StructField("ModalitiesInStudy", ArrayType(StringType()), nullable=True),
            StructField("NumberOfStudyRelatedSeries", IntegerType(), nullable=True),
            StructField("NumberOfStudyRelatedInstances", IntegerType(), nullable=True),
            StructField("connection_name", StringType(), nullable=True),
        ]
    )

    SERIES_SCHEMA = StructType(
        [
            StructField("SeriesInstanceUID", StringType(), nullable=False),
            StructField("StudyInstanceUID", StringType(), nullable=True),
            StructField("StudyDate", StringType(), nullable=True),
            StructField("SeriesNumber", IntegerType(), nullable=True),
            StructField("SeriesDescription", StringType(), nullable=True),
            StructField("Modality", StringType(), nullable=True),
            StructField("BodyPartExamined", StringType(), nullable=True),
            StructField("SeriesDate", StringType(), nullable=True),
            StructField("connection_name", StringType(), nullable=True),
        ]
    )

    INSTANCES_SCHEMA = StructType(
        [
            StructField("SOPInstanceUID", StringType(), nullable=False),
            StructField("SeriesInstanceUID", StringType(), nullable=True),
            StructField("StudyInstanceUID", StringType(), nullable=True),
            StructField("SOPClassUID", StringType(), nullable=True),
            StructField("InstanceNumber", IntegerType(), nullable=True),
            StructField("StudyDate", StringType(), nullable=True),
            StructField("ContentDate", StringType(), nullable=True),
            StructField("ContentTime", StringType(), nullable=True),
            StructField("dicom_file_path", StringType(), nullable=True),
            StructField("metadata", VariantType(), nullable=True),
            StructField("connection_name", StringType(), nullable=True),
        ]
    )

    DIAGNOSTICS_SCHEMA = StructType(
        [
            StructField("endpoint", StringType(), nullable=False),
            StructField("category", StringType(), nullable=True),
            StructField("description", StringType(), nullable=True),
            StructField("supported", StringType(), nullable=False),
            StructField("status_code", IntegerType(), nullable=True),
            StructField("content_type", StringType(), nullable=True),
            StructField("latency_ms", IntegerType(), nullable=True),
            StructField("notes", StringType(), nullable=True),
            StructField("probe_timestamp", StringType(), nullable=False),
            StructField("connection_name", StringType(), nullable=True),
        ]
    )

    _TABLE_SCHEMAS = {
        "studies": STUDIES_SCHEMA,
        "series": SERIES_SCHEMA,
        "instances": INSTANCES_SCHEMA,
        "diagnostics": DIAGNOSTICS_SCHEMA,
    }

    ########################################################
    # sources/dicomweb/dicomweb_client.py
    ########################################################

    _DEFAULT_TIMEOUT = (10, 60)

    class DICOMwebClient:
        def __init__(
            self,
            base_url: str,
            auth_type: str = "none",
            username: str | None = None,
            password: str | None = None,
            token: str | None = None,
            timeout: tuple = _DEFAULT_TIMEOUT,
        ) -> None:
            self.base_url = base_url.rstrip("/")
            self.timeout = timeout
            self._session = requests.Session()
            self._session.headers.update({"Accept": "application/dicom+json"})
            auth_type = (auth_type or "none").lower()
            if auth_type == "basic":
                if not username or not password:
                    raise ValueError("auth_type=basic requires username and password")
                self._session.auth = HTTPBasicAuth(username, password)
            elif auth_type == "bearer":
                if not token:
                    raise ValueError("auth_type=bearer requires token")
                self._session.headers["Authorization"] = f"Bearer {token}"
            elif auth_type != "none":
                raise ValueError(f"Unsupported auth_type '{auth_type}'. Use: none, basic, bearer")

        def _qido_get(self, path: str, params: dict) -> list:
            url = f"{self.base_url}{path}"
            resp = self._session.get(url, params=params, timeout=self.timeout)
            if resp.status_code == 204:
                return []
            resp.raise_for_status()
            if not resp.content:
                return []
            return resp.json()

        def query_studies(self, study_date_range: str, limit: int = 100, offset: int = 0) -> list:
            return self._qido_get("/studies", {"StudyDate": study_date_range, "limit": limit, "offset": offset})

        def query_series_for_study(self, study_uid: str) -> list:
            """QIDO-RS: GET /studies/{study_uid}/series — hierarchical series endpoint."""
            return self._qido_get(f"/studies/{study_uid}/series", {})

        def query_instances_for_series(self, study_uid: str, series_uid: str) -> list:
            """QIDO-RS: GET /studies/{study_uid}/series/{series_uid}/instances — hierarchical instances endpoint."""
            return self._qido_get(f"/studies/{study_uid}/series/{series_uid}/instances", {})

        def retrieve_instance(self, study_uid: str, series_uid: str, sop_uid: str) -> bytes:
            url = f"{self.base_url}/studies/{study_uid}/series/{series_uid}/instances/{sop_uid}"
            resp = self._session.get(
                url,
                headers={"Accept": 'multipart/related; type="application/dicom"'},
                timeout=self.timeout,
            )
            resp.raise_for_status()
            content_type = resp.headers.get("Content-Type", "")
            if "multipart/related" in content_type:
                return _extract_first_multipart_part(resp.content, content_type)
            return resp.content

        def retrieve_instance_frames(
            self, study_uid: str, series_uid: str, sop_uid: str, frame_number: int = 1
        ) -> bytes:
            """WADO-RS: GET .../instances/{sop_uid}/frames/{n} — frame-based retrieval for S3 Static WADO."""
            url = f"{self.base_url}/studies/{study_uid}/series/{series_uid}/instances/{sop_uid}/frames/{frame_number}"
            resp = self._session.get(
                url,
                headers={"Accept": "image/jpeg, image/png, application/octet-stream"},
                timeout=self.timeout,
            )
            resp.raise_for_status()
            content_type = resp.headers.get("Content-Type", "")
            if "multipart/related" in content_type:
                return _extract_first_multipart_part(resp.content, content_type)
            return resp.content

        def retrieve_instance_metadata(self, study_uid: str, series_uid: str, sop_uid: str) -> dict:
            """WADO-RS: GET .../instances/{uid}/metadata — full DICOM JSON for a single instance."""
            url = f"{self.base_url}/studies/{study_uid}/series/{series_uid}/instances/{sop_uid}/metadata"
            resp = self._session.get(url, headers={"Accept": "application/dicom+json"}, timeout=self.timeout)
            if resp.status_code == 204:
                return {}
            resp.raise_for_status()
            if not resp.content:
                return {}
            data = resp.json()
            if isinstance(data, list):
                return data[0] if data else {}
            return data

        def retrieve_series_metadata(self, study_uid: str, series_uid: str) -> list:
            """WADO-RS: GET .../series/{uid}/metadata — full DICOM JSON for all instances in a series."""
            url = f"{self.base_url}/studies/{study_uid}/series/{series_uid}/metadata"
            resp = self._session.get(url, headers={"Accept": "application/dicom+json"}, timeout=self.timeout)
            if resp.status_code == 204:
                return []
            resp.raise_for_status()
            if not resp.content:
                return []
            return resp.json()

        def probe_endpoint(self, path: str, accept=None) -> dict:
            """Probe a DICOMweb endpoint and return capability information without raising exceptions."""
            url = f"{self.base_url}{path}"
            headers = {"Accept": accept} if accept else {}
            t0 = time.monotonic()
            try:
                resp = self._session.get(url, headers=headers or None, timeout=self.timeout)
                return {
                    "status_code": resp.status_code,
                    "content_type": resp.headers.get("Content-Type", ""),
                    "latency_ms": int((time.monotonic() - t0) * 1000),
                    "error": None,
                }
            except Exception as exc:
                return {
                    "status_code": None,
                    "content_type": None,
                    "latency_ms": int((time.monotonic() - t0) * 1000),
                    "error": str(exc),
                }

    def _parse_boundary(content_type: str) -> str | None:
        for segment in content_type.split(";"):
            segment = segment.strip()
            if segment.lower().startswith("boundary="):
                return segment[len("boundary=") :].strip().strip('"')
        return None

    def _extract_first_multipart_part(body: bytes, content_type: str) -> bytes:
        boundary = _parse_boundary(content_type)
        if not boundary:
            return body
        sep = f"--{boundary}".encode()
        parts = body.split(sep)
        for part in parts[1:]:
            if part.strip() in (b"", b"--", b"--\r\n", b"--\n"):
                continue
            if b"\r\n\r\n" in part:
                return part.split(b"\r\n\r\n", 1)[1].rstrip(b"\r\n")
            if b"\n\n" in part:
                return part.split(b"\n\n", 1)[1].rstrip(b"\n")
            return part
        return body

    ########################################################
    # sources/dicomweb/dicomweb.py
    ########################################################

    _SUPPORTED_TABLES = ("studies", "series", "instances", "diagnostics")
    _DEFAULT_START_DATE = "19000101"
    _DEFAULT_PAGE_SIZE = 100
    _DEFAULT_LOOKBACK_DAYS = 1
    _WADO_MODE_AUTO = "auto"
    _WADO_MODE_FULL = "full"
    _WADO_MODE_FRAMES = "frames"

    def _subtract_days(date_str: str, days: int) -> str:
        if date_str == _DEFAULT_START_DATE or days == 0:
            return date_str
        try:
            d = date(int(date_str[:4]), int(date_str[4:6]), int(date_str[6:8]))
            return (d - timedelta(days=days)).strftime("%Y%m%d")
        except (ValueError, IndexError):
            return date_str

    class DICOMwebLakeflowConnect(LakeflowConnect):
        def __init__(self, options: dict[str, str]) -> None:
            super().__init__(options)
            base_url = options.get("base_url")
            if not base_url:
                raise ValueError("Connection option 'base_url' is required")
            self._client = DICOMwebClient(
                base_url=base_url,
                auth_type=options.get("auth_type", "none"),
                username=options.get("username"),
                password=options.get("password"),
                token=options.get("token"),
            )
            self._connection_name = options.get("connection_name") or base_url
            self._wado_mode_detected = None

        def list_tables(self) -> list[str]:
            return list(_SUPPORTED_TABLES)

        def get_table_schema(self, table_name: str, table_options: dict[str, str]) -> StructType:
            if table_name not in _TABLE_SCHEMAS:
                raise ValueError(f"Unknown table '{table_name}'")
            return _TABLE_SCHEMAS[table_name]

        def read_table_metadata(self, table_name: str, table_options: dict[str, str]) -> dict:
            if table_name == "diagnostics":
                return {"primary_keys": ["endpoint"], "cursor_field": "probe_timestamp", "ingestion_type": "cdc"}
            pk_map = {
                "studies": "StudyInstanceUID",
                "series": "SeriesInstanceUID",
                "instances": "SOPInstanceUID",
            }
            return {"primary_keys": [pk_map[table_name]], "cursor_field": "StudyDate", "ingestion_type": "cdc"}

        def read_table(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            if table_name not in _SUPPORTED_TABLES:
                raise ValueError(f"Unknown table '{table_name}'")

            if table_name == "diagnostics":
                return self._run_diagnostics_probe(), {"probe_timestamp": datetime.now(tz=timezone.utc).isoformat()}

            start_offset = start_offset or {}
            page_size = int(table_options.get("page_size", _DEFAULT_PAGE_SIZE))
            lookback_days = int(table_options.get("lookback_days", _DEFAULT_LOOKBACK_DAYS))
            date_cursor = start_offset.get("study_date", _DEFAULT_START_DATE)
            page_offset = start_offset.get("page_offset", 0)
            today_str = date.today().strftime("%Y%m%d")
            effective_start = _subtract_days(date_cursor, lookback_days)
            date_range = f"{effective_start}-{today_str}"

            fetch_files = table_options.get("fetch_dicom_files", "false").lower() == "true"
            volume_path = table_options.get("dicom_volume_path", "")
            fetch_metadata = table_options.get("fetch_metadata", "false").lower() == "true"
            wado_mode = table_options.get("wado_mode", _WADO_MODE_AUTO).lower()
            if fetch_files and not volume_path and table_name == "instances":
                raise ValueError("fetch_dicom_files=true requires dicom_volume_path to be set")

            records_iter = self._paginate(
                table_name, date_range, page_size, page_offset, fetch_files, volume_path, fetch_metadata, wado_mode
            )
            next_offset = {"study_date": today_str, "page_offset": 0}
            return records_iter, next_offset

        def _paginate(
            self, table_name, date_range, page_size, start_offset, fetch_files, volume_path, fetch_metadata, wado_mode
        ):
            if table_name == "studies":
                yield from self._paginate_studies(date_range, page_size, start_offset)
            elif table_name == "series":
                yield from self._paginate_series(date_range, page_size, start_offset)
            else:
                yield from self._paginate_instances(
                    date_range, page_size, start_offset, fetch_files, volume_path, fetch_metadata, wado_mode
                )

        def _paginate_studies(self, date_range, page_size, start_offset):
            offset = start_offset
            while True:
                raw_records = self._client.query_studies(date_range, limit=page_size, offset=offset)
                if not raw_records:
                    break
                for raw in raw_records:
                    record = _parse_study(raw)
                    record["connection_name"] = self._connection_name
                    yield record
                if len(raw_records) < page_size:
                    break
                offset += page_size

        def _paginate_series(self, date_range, page_size, start_offset):
            study_offset = start_offset
            while True:
                studies = self._client.query_studies(date_range, limit=page_size, offset=study_offset)
                if not studies:
                    break
                for study_raw in studies:
                    study = _parse_study(study_raw)
                    study_uid = study.get("StudyInstanceUID")
                    if not study_uid:
                        continue
                    for series_raw in self._client.query_series_for_study(study_uid):
                        record = _parse_series(series_raw)
                        if not record.get("StudyDate"):
                            record["StudyDate"] = study.get("StudyDate")
                        if not record.get("StudyInstanceUID"):
                            record["StudyInstanceUID"] = study_uid
                        record["connection_name"] = self._connection_name
                        yield record
                if len(studies) < page_size:
                    break
                study_offset += page_size

        def _paginate_instances(
            self, date_range, page_size, start_offset, fetch_files, volume_path, fetch_metadata, wado_mode
        ):
            study_offset = start_offset
            while True:
                studies = self._client.query_studies(date_range, limit=page_size, offset=study_offset)
                if not studies:
                    break
                for study_raw in studies:
                    study = _parse_study(study_raw)
                    study_uid = study.get("StudyInstanceUID")
                    if not study_uid:
                        continue
                    for series_raw in self._client.query_series_for_study(study_uid):
                        series = _parse_series(series_raw)
                        series_uid = series.get("SeriesInstanceUID")
                        if not series_uid:
                            continue
                        sop_to_meta = self._build_metadata_map(study_uid, series_uid) if fetch_metadata else {}
                        for inst_raw in self._client.query_instances_for_series(study_uid, series_uid):
                            record = _parse_instance(inst_raw)
                            if not record.get("StudyDate"):
                                record["StudyDate"] = study.get("StudyDate")
                            if not record.get("StudyInstanceUID"):
                                record["StudyInstanceUID"] = study_uid
                            if not record.get("SeriesInstanceUID"):
                                record["SeriesInstanceUID"] = series_uid
                            if fetch_metadata:
                                sop_uid = record.get("SOPInstanceUID")
                                record["metadata"] = sop_to_meta.get(sop_uid) if sop_uid else None
                            if fetch_files:
                                record = self._attach_dicom_file(record, volume_path, wado_mode)
                            record["connection_name"] = self._connection_name
                            yield record
                if len(studies) < page_size:
                    break
                study_offset += page_size

        def _resolve_wado_mode(self, wado_mode):
            if wado_mode == _WADO_MODE_AUTO:
                return self._wado_mode_detected or _WADO_MODE_FULL
            return wado_mode

        def _build_metadata_map(self, study_uid, series_uid):
            try:
                meta_list = self._client.retrieve_series_metadata(study_uid, series_uid)
                sop_to_meta = {}
                for meta_obj in meta_list:
                    tag_obj = meta_obj.get("00080018")
                    if tag_obj and tag_obj.get("Value"):
                        sop_uid = str(tag_obj["Value"][0])
                        sop_to_meta[sop_uid] = json.dumps(meta_obj)
                return sop_to_meta
            except Exception:
                return {}

        def _run_diagnostics_probe(self):
            probe_timestamp = datetime.now(tz=timezone.utc).isoformat()
            study_uid = series_uid = sop_uid = None
            try:
                studies = self._client.query_studies("19000101-99991231", limit=1, offset=0)
                if studies:
                    tag = studies[0].get("0020000D")
                    study_uid = str(tag["Value"][0]) if tag and tag.get("Value") else None
            except Exception:
                pass
            if study_uid:
                try:
                    sl = self._client.query_series_for_study(study_uid)
                    if sl:
                        tag = sl[0].get("0020000E")
                        series_uid = str(tag["Value"][0]) if tag and tag.get("Value") else None
                except Exception:
                    pass
            if study_uid and series_uid:
                try:
                    il = self._client.query_instances_for_series(study_uid, series_uid)
                    if il:
                        tag = il[0].get("00080018")
                        sop_uid = str(tag["Value"][0]) if tag and tag.get("Value") else None
                except Exception:
                    pass

            probes = [
                ("/studies", "/studies?limit=1", "QIDO-RS", "Search studies (flat pagination)", None),
                (
                    "/studies/{uid}/series",
                    f"/studies/{study_uid}/series" if study_uid else None,
                    "QIDO-RS",
                    "Search series for a study (hierarchical)",
                    None,
                ),
                (
                    "/studies/{uid}/series/{uid}/instances",
                    f"/studies/{study_uid}/series/{series_uid}/instances" if study_uid and series_uid else None,
                    "QIDO-RS",
                    "Search instances for a series (hierarchical)",
                    None,
                ),
                (
                    "/studies/{uid}/series/{uid}/metadata",
                    f"/studies/{study_uid}/series/{series_uid}/metadata" if study_uid and series_uid else None,
                    "WADO-RS",
                    "Series metadata — full DICOM JSON for all instances",
                    "application/dicom+json",
                ),
                (
                    "/studies/{uid}/series/{uid}/instances/{uid}/metadata",
                    f"/studies/{study_uid}/series/{series_uid}/instances/{sop_uid}/metadata"
                    if study_uid and series_uid and sop_uid
                    else None,
                    "WADO-RS",
                    "Instance metadata — full DICOM JSON for a single instance",
                    "application/dicom+json",
                ),
                (
                    "/studies/{uid}/series/{uid}/instances/{uid}",
                    f"/studies/{study_uid}/series/{series_uid}/instances/{sop_uid}"
                    if study_uid and series_uid and sop_uid
                    else None,
                    "WADO-RS",
                    "Retrieve full DICOM instance (.dcm)",
                    'multipart/related; type="application/dicom"',
                ),
                (
                    "/studies/{uid}/series/{uid}/instances/{uid}/frames/{n}",
                    f"/studies/{study_uid}/series/{series_uid}/instances/{sop_uid}/frames/1"
                    if study_uid and series_uid and sop_uid
                    else None,
                    "WADO-RS",
                    "Retrieve pixel frame (image/jpeg or image/jls)",
                    "image/jpeg, image/jls, application/octet-stream",
                ),
                (
                    "/studies/{uid}/series/{uid}/instances/{uid}/rendered",
                    f"/studies/{study_uid}/series/{series_uid}/instances/{sop_uid}/rendered"
                    if study_uid and series_uid and sop_uid
                    else None,
                    "WADO-RS",
                    "Retrieve rendered instance (PNG/JPEG)",
                    "image/jpeg, image/png",
                ),
                (
                    "/studies/{uid}/series/{uid}/rendered",
                    f"/studies/{study_uid}/series/{series_uid}/rendered" if study_uid and series_uid else None,
                    "WADO-RS",
                    "Retrieve rendered series",
                    "image/jpeg, image/png",
                ),
                (
                    "/studies/{uid}",
                    f"/studies/{study_uid}" if study_uid else None,
                    "WADO-RS",
                    "Retrieve entire study (all instances, multipart/related)",
                    'multipart/related; type="application/dicom"',
                ),
            ]

            for endpoint_pattern, path, category, description, accept in probes:
                if path is None:
                    yield {
                        "endpoint": endpoint_pattern,
                        "category": category,
                        "description": description,
                        "supported": "unknown",
                        "status_code": None,
                        "content_type": None,
                        "latency_ms": None,
                        "notes": "Could not probe — no sample UID available from the server",
                        "probe_timestamp": probe_timestamp,
                        "connection_name": self._connection_name,
                    }
                    continue
                result = self._client.probe_endpoint(path, accept=accept)
                status = result["status_code"]
                if result["error"]:
                    supported, notes = "error", result["error"]
                elif status in (200, 204, 206):
                    supported, notes = "yes", f"Content-Type: {result['content_type']}"
                elif status == 400:
                    supported, notes = "partial", "Bad Request (400) — endpoint exists but may require query parameters"
                elif status == 403:
                    supported, notes = "no", "Access Denied (403) — endpoint blocked by server or CDN policy"
                elif status == 404:
                    supported, notes = "no", "Not Found (404) — endpoint not implemented on this server"
                elif status == 406:
                    supported, notes = "no", "Not Acceptable (406) — requested media type not supported"
                else:
                    supported, notes = "no", f"HTTP {status}"
                yield {
                    "endpoint": endpoint_pattern,
                    "category": category,
                    "description": description,
                    "supported": supported,
                    "status_code": status,
                    "content_type": result["content_type"],
                    "latency_ms": result["latency_ms"],
                    "notes": notes,
                    "probe_timestamp": probe_timestamp,
                    "connection_name": self._connection_name,
                }

        def _attach_dicom_file(self, record: dict, volume_path: str, wado_mode: str) -> dict:
            study_uid = record.get("StudyInstanceUID")
            series_uid = record.get("SeriesInstanceUID")
            sop_uid = record.get("SOPInstanceUID")
            if not all([study_uid, series_uid, sop_uid]):
                return record
            try:
                effective_mode = self._resolve_wado_mode(wado_mode)
                if effective_mode == _WADO_MODE_FRAMES:
                    file_bytes = self._client.retrieve_instance_frames(study_uid, series_uid, sop_uid)
                    ext = ".jpg"
                else:
                    try:
                        file_bytes = self._client.retrieve_instance(study_uid, series_uid, sop_uid)
                        ext = ".dcm"
                        if wado_mode == _WADO_MODE_AUTO and self._wado_mode_detected is None:
                            self._wado_mode_detected = _WADO_MODE_FULL
                    except Exception as exc:
                        status = getattr(getattr(exc, "response", None), "status_code", None)
                        if wado_mode == _WADO_MODE_AUTO and status in (404, 406, 415):
                            self._wado_mode_detected = _WADO_MODE_FRAMES
                            file_bytes = self._client.retrieve_instance_frames(study_uid, series_uid, sop_uid)
                            ext = ".jpg"
                        else:
                            raise
                dest_path = pathlib.Path(volume_path) / study_uid / series_uid / f"{sop_uid}{ext}"
                try:
                    dest_path.parent.mkdir(parents=True, exist_ok=True)
                except OSError:
                    pass
                dest_path.write_bytes(file_bytes)
                record["dicom_file_path"] = str(dest_path)
            except Exception as exc:
                logging.getLogger(__name__).error("WADO-RS retrieval failed for %s: %s", sop_uid, exc)
                record["dicom_file_path"] = None
            return record

    ########################################################
    # src/databricks/labs/community_connector/sparkpds/lakeflow_datasource.py
    ########################################################

    LakeflowConnectImpl = DICOMwebLakeflowConnect
    METADATA_TABLE = "_lakeflow_metadata"
    TABLE_NAME = "tableName"
    TABLE_NAME_LIST = "tableNameList"
    TABLE_CONFIGS = "tableConfigs"
    IS_DELETE_FLOW = "isDeleteFlow"
    FETCH_DICOM_FILES = "fetch_dicom_files"
    DICOM_VOLUME_PATH = "dicom_volume_path"
    MAX_CONCURRENT_REQUESTS = "max_concurrent_requests"
    WADO_MODE = "wado_mode"
    _DEFAULT_MAX_CONCURRENT_REQUESTS = 16

    @dataclass
    class SimplePartition(InputPartition):
        """Single-partition descriptor for metadata-only tables."""

        start_json: str

    @dataclass
    class DicomBatchPartition(InputPartition):
        """
        A batch of DICOM instances for one Spark task.

        Grouping multiple instances per partition bounds the total number of
        simultaneous Spark tasks (= concurrent WADO-RS connections to the PACS)
        to max_concurrent_requests, regardless of cluster size.
        Each worker downloads its batch sequentially.
        """

        instances_json: str  # JSON array of {record, dest_path, study_uid, series_uid, sop_uid}

    class DicomStreamReader(DataSourceStreamReader):
        """
        Multi-partition streaming reader.

        For instances + fetch_dicom_files=true:
            partitions() runs on the driver — queries QIDO-RS, groups results
            into at most max_concurrent_requests batches, and returns one
            DicomBatchPartition per batch.  Spark schedules each batch as a
            separate task on a worker node, so at most max_concurrent_requests
            WADO-RS connections are open against the PACS simultaneously.
            read(partition) runs on each worker — recreates the HTTP client
            and downloads the files in its batch sequentially.

        For all other cases:
            Returns a single SimplePartition so all records are streamed on
            one worker (same behaviour as SimpleDataSourceStreamReader).
        """

        def __init__(self, options, schema):
            self.options = options
            self.schema = schema

        def _make_connector(self):
            return DICOMwebLakeflowConnect(self.options)

        def initialOffset(self):
            return {}

        def latestOffset(self):
            return {"study_date": date.today().strftime("%Y%m%d"), "page_offset": 0}

        def partitions(self, start, end):
            import math

            table = self.options.get(TABLE_NAME, "")
            fetch_files = self.options.get(FETCH_DICOM_FILES, "false").lower() == "true"
            volume_path = self.options.get(DICOM_VOLUME_PATH, "")
            wado_mode = self.options.get(WADO_MODE, _WADO_MODE_AUTO).lower()
            max_concurrent = int(self.options.get(MAX_CONCURRENT_REQUESTS, _DEFAULT_MAX_CONCURRENT_REQUESTS))

            if table == "instances" and fetch_files:
                # Driver: collect metadata without WADO-RS, then group instances
                # into at most max_concurrent batches.
                metadata_options = {**self.options, FETCH_DICOM_FILES: "false"}
                connector = self._make_connector()
                records, _ = connector.read_table(table, start or {}, metadata_options)

                instances = []
                for record in records:
                    study_uid = record.get("StudyInstanceUID") or ""
                    series_uid = record.get("SeriesInstanceUID") or ""
                    sop_uid = record.get("SOPInstanceUID") or ""
                    # Placeholder extension — worker will determine actual ext based on wado_mode
                    ext = ".dcm" if wado_mode != _WADO_MODE_FRAMES else ".jpg"
                    dest = (
                        str(pathlib.Path(volume_path) / study_uid / series_uid / f"{sop_uid}{ext}")
                        if volume_path and study_uid and series_uid and sop_uid
                        else ""
                    )
                    instances.append(
                        {
                            "record": record,
                            "dest_path": dest,
                            "study_uid": study_uid,
                            "series_uid": series_uid,
                            "sop_uid": sop_uid,
                        }
                    )

                if not instances:
                    return []

                # Divide into at most max_concurrent batches so the number of
                # simultaneous Spark tasks (= simultaneous PACS connections) is
                # bounded by max_concurrent_requests.
                batch_size = max(1, math.ceil(len(instances) / max_concurrent))
                batches = [instances[i : i + batch_size] for i in range(0, len(instances), batch_size)]
                return [DicomBatchPartition(instances_json=json.dumps(batch, default=str)) for batch in batches]
            else:
                # Single partition: stream all records on one worker.
                return [SimplePartition(start_json=json.dumps(start or {}))]

        def read(self, partition):
            if isinstance(partition, DicomBatchPartition):
                # Worker: download each file in the batch sequentially and yield rows.
                instances = json.loads(partition.instances_json)
                wado_mode = self.options.get(WADO_MODE, _WADO_MODE_AUTO).lower()
                client = DICOMwebClient(
                    base_url=self.options.get("base_url", ""),
                    auth_type=self.options.get("auth_type", "none"),
                    username=self.options.get("username"),
                    password=self.options.get("password"),
                    token=self.options.get("token"),
                )
                # Per-worker wado_mode detection cache
                detected_mode = None
                rows = []
                for inst in instances:
                    record = inst["record"]
                    if inst.get("study_uid") and inst.get("sop_uid"):
                        try:
                            effective = detected_mode or (
                                wado_mode if wado_mode != _WADO_MODE_AUTO else _WADO_MODE_FULL
                            )
                            if effective == _WADO_MODE_FRAMES:
                                file_bytes = client.retrieve_instance_frames(
                                    inst["study_uid"], inst["series_uid"], inst["sop_uid"]
                                )
                                ext = ".jpg"
                            else:
                                try:
                                    file_bytes = client.retrieve_instance(
                                        inst["study_uid"], inst["series_uid"], inst["sop_uid"]
                                    )
                                    ext = ".dcm"
                                    if wado_mode == _WADO_MODE_AUTO and detected_mode is None:
                                        detected_mode = _WADO_MODE_FULL
                                except Exception as exc:
                                    status = getattr(getattr(exc, "response", None), "status_code", None)
                                    if wado_mode == _WADO_MODE_AUTO and status in (404, 406, 415):
                                        detected_mode = _WADO_MODE_FRAMES
                                        file_bytes = client.retrieve_instance_frames(
                                            inst["study_uid"], inst["series_uid"], inst["sop_uid"]
                                        )
                                        ext = ".jpg"
                                    else:
                                        raise
                            volume_path = self.options.get(DICOM_VOLUME_PATH, "")
                            dest = (
                                pathlib.Path(volume_path)
                                / inst["study_uid"]
                                / inst["series_uid"]
                                / f"{inst['sop_uid']}{ext}"
                            )
                            try:
                                dest.parent.mkdir(parents=True, exist_ok=True)
                            except OSError:
                                pass
                            dest.write_bytes(file_bytes)
                            record["dicom_file_path"] = str(dest)
                        except Exception as exc:
                            logging.getLogger(__name__).error("WADO-RS failed for %s: %s", inst.get("sop_uid"), exc)
                            record["dicom_file_path"] = None
                    rows.append(parse_value(record, self.schema))
                return iter(rows)
            else:
                # Single partition: stream all records for the table.
                start = json.loads(partition.start_json)
                table_options = {k: v for k, v in self.options.items() if k != IS_DELETE_FLOW}
                connector = self._make_connector()
                records, _ = connector.read_table(self.options[TABLE_NAME], start, table_options)
                return map(lambda x: parse_value(x, self.schema), records)

        def commit(self, end):
            pass

    class LakeflowStreamReader(SimpleDataSourceStreamReader):
        def __init__(self, options, schema, lakeflow_connect):
            self.options = options
            self.lakeflow_connect = lakeflow_connect
            self.schema = schema

        def initialOffset(self):
            return {}

        def read(self, start: dict) -> tuple:
            is_delete_flow = self.options.get(IS_DELETE_FLOW) == "true"
            table_options = {k: v for k, v in self.options.items() if k != IS_DELETE_FLOW}
            if is_delete_flow:
                records, offset = self.lakeflow_connect.read_table_deletes(
                    self.options[TABLE_NAME], start, table_options
                )
            else:
                records, offset = self.lakeflow_connect.read_table(self.options[TABLE_NAME], start, table_options)
            rows = map(lambda x: parse_value(x, self.schema), records)
            return rows, offset

        def readBetweenOffsets(self, start: dict, end: dict) -> Iterator:
            return self.read(start)[0]

    class LakeflowBatchReader(DataSourceReader):
        def __init__(self, options, schema, lakeflow_connect):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]

        def read(self, partition):
            if self.table_name == METADATA_TABLE:
                all_records = self._read_table_metadata()
            else:
                all_records, _ = self.lakeflow_connect.read_table(self.table_name, None, self.options)
            return iter(map(lambda x: parse_value(x, self.schema), all_records))

        def _read_table_metadata(self):
            table_names = [o.strip() for o in self.options.get(TABLE_NAME_LIST, "").split(",") if o.strip()]
            table_configs = json.loads(self.options.get(TABLE_CONFIGS, "{}"))
            return [
                {TABLE_NAME: t, **self.lakeflow_connect.read_table_metadata(t, table_configs.get(t, {}))}
                for t in table_names
            ]

    class LakeflowSource(DataSource):
        def __init__(self, options):
            self.options = options
            self.lakeflow_connect = LakeflowConnectImpl(options)

        @classmethod
        def name(cls):
            return "lakeflow_connect"

        def schema(self):
            table = self.options[TABLE_NAME]
            if table == METADATA_TABLE:
                return StructType(
                    [
                        StructField(TABLE_NAME, StringType(), False),
                        StructField("primary_keys", ArrayType(StringType()), True),
                        StructField("cursor_field", StringType(), True),
                        StructField("ingestion_type", StringType(), True),
                    ]
                )
            return self.lakeflow_connect.get_table_schema(table, self.options)

        def reader(self, schema: StructType):
            return LakeflowBatchReader(self.options, schema, self.lakeflow_connect)

        def streamReader(self, schema: StructType):
            return DicomStreamReader(self.options, schema)

    spark.dataSource.register(LakeflowSource)
