# ==============================================================================
# Merged Lakeflow Source: dicomweb
# ==============================================================================
# This file is auto-generated by tools/scripts/merge_python_source.py
# Do not edit manually. Make changes to the source files instead.
# ==============================================================================

from abc import ABC, abstractmethod
from concurrent.futures import ThreadPoolExecutor
from datetime import date, timedelta
from decimal import Decimal
from typing import Any, Iterator
import json
import logging
import pathlib

from requests.auth import HTTPBasicAuth
from pyspark.sql import Row
from pyspark.sql.datasource import DataSource, DataSourceReader, SimpleDataSourceStreamReader
from pyspark.sql.types import (
    ArrayType, BinaryType, BooleanType, ByteType, DataType, DateType,
    DecimalType, DoubleType, FloatType, IntegerType, LongType, MapType,
    ShortType, StringType, StructField, StructType, TimestampType,
)
import requests


def register_lakeflow_source(spark):
    """Register the DICOMweb Lakeflow Python source with Spark."""

    ########################################################
    # src/databricks/labs/community_connector/libs/utils.py
    ########################################################

    def _parse_struct(value: Any, field_type: StructType) -> Row:
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for StructType, got {type(value)}")
        if value == {}:
            raise ValueError(
                "field in StructType cannot be an empty dict. "
                "Please assign None as the default value instead."
            )
        field_dict = {}
        for field in field_type.fields:
            if field.name in value:
                field_dict[field.name] = parse_value(value.get(field.name), field.dataType)
            elif field.nullable:
                field_dict[field.name] = None
            else:
                raise ValueError(f"Field {field.name} is not nullable but not found in the input")
        return Row(**field_dict)

    def _parse_array(value: Any, field_type: ArrayType) -> list:
        if not isinstance(value, list):
            if field_type.containsNull:
                return [parse_value(value, field_type.elementType)]
            raise ValueError(f"Expected a list for ArrayType, got {type(value)}")
        return [parse_value(v, field_type.elementType) for v in value]

    def _parse_map(value: Any, field_type: MapType) -> dict:
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for MapType, got {type(value)}")
        return {
            parse_value(k, field_type.keyType): parse_value(v, field_type.valueType)
            for k, v in value.items()
        }

    def _parse_string(value: Any) -> str:
        return str(value)

    def _parse_integer(value: Any) -> int:
        if isinstance(value, str) and value.strip():
            return int(float(value)) if "." in value else int(value)
        if isinstance(value, (int, float)):
            return int(value)
        raise ValueError(f"Cannot convert {value} to integer")

    def _parse_float(value: Any) -> float:
        return float(value)

    def _parse_decimal(value: Any) -> Decimal:
        return Decimal(value) if isinstance(value, str) and value.strip() else Decimal(str(value))

    def _parse_boolean(value: Any) -> bool:
        if isinstance(value, str):
            lowered = value.lower()
            if lowered in ("true", "t", "yes", "y", "1"):
                return True
            if lowered in ("false", "f", "no", "n", "0"):
                return False
        return bool(value)

    def _parse_binary(value: Any) -> bytes:
        if isinstance(value, bytes):
            return value
        if isinstance(value, bytearray):
            return bytes(value)
        if isinstance(value, str):
            import base64
            try:
                return base64.b64decode(value)
            except Exception:
                return value.encode("utf-8")
        return str(value).encode("utf-8")

    _PRIMITIVE_PARSERS = {
        StringType: _parse_string,
        IntegerType: _parse_integer,
        LongType: _parse_integer,
        ShortType: _parse_integer,
        ByteType: _parse_integer,
        FloatType: _parse_float,
        DoubleType: _parse_float,
        DecimalType: _parse_decimal,
        BooleanType: _parse_boolean,
        BinaryType: _parse_binary,
    }

    def parse_value(value: Any, field_type: DataType) -> Any:
        if value is None:
            return None
        if isinstance(field_type, StructType):
            return _parse_struct(value, field_type)
        if isinstance(field_type, ArrayType):
            return _parse_array(value, field_type)
        if isinstance(field_type, MapType):
            return _parse_map(value, field_type)
        field_type_class = type(field_type)
        if field_type_class in _PRIMITIVE_PARSERS:
            return _PRIMITIVE_PARSERS[field_type_class](value)
        return value

    ########################################################
    # src/databricks/labs/community_connector/interface/lakeflow_connect.py
    ########################################################

    class LakeflowConnect(ABC):
        def __init__(self, options: dict[str, str]) -> None:
            self.options = options

        @abstractmethod
        def list_tables(self) -> list[str]: ...

        @abstractmethod
        def get_table_schema(self, table_name: str, table_options: dict[str, str]) -> StructType: ...

        @abstractmethod
        def read_table_metadata(self, table_name: str, table_options: dict[str, str]) -> dict: ...

        @abstractmethod
        def read_table(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]: ...

        def read_table_deletes(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            raise NotImplementedError

    ########################################################
    # sources/dicomweb/dicomweb_parser.py
    ########################################################

    STUDY_TAG_MAP = {
        "0020000D": "StudyInstanceUID",
        "00080020": "StudyDate",
        "00080030": "StudyTime",
        "00080050": "AccessionNumber",
        "00100010": "PatientName",
        "00100020": "PatientID",
        "00081030": "StudyDescription",
        "00080061": "ModalitiesInStudy",
        "00201206": "NumberOfStudyRelatedSeries",
        "00201208": "NumberOfStudyRelatedInstances",
    }

    SERIES_TAG_MAP = {
        "0020000E": "SeriesInstanceUID",
        "0020000D": "StudyInstanceUID",
        "00080020": "StudyDate",
        "00200011": "SeriesNumber",
        "0008103E": "SeriesDescription",
        "00080060": "Modality",
        "00180015": "BodyPartExamined",
        "00080021": "SeriesDate",
    }

    INSTANCE_TAG_MAP = {
        "00080018": "SOPInstanceUID",
        "0020000E": "SeriesInstanceUID",
        "0020000D": "StudyInstanceUID",
        "00080016": "SOPClassUID",
        "00200013": "InstanceNumber",
        "00080020": "StudyDate",
        "00080023": "ContentDate",
        "00080033": "ContentTime",
    }

    _STRING_VRS = {"DA", "TM", "CS", "LO", "UI", "SH", "LT", "ST", "UT", "AE", "AS", "DT", "UC", "UR"}
    _NUMERIC_VRS = {"IS", "DS", "FL", "FD", "SL", "SS", "UL", "US"}

    def _extract_dicom_value(tag_obj: dict, field_name: str) -> object:
        vr = tag_obj.get("vr", "")
        values = tag_obj.get("Value", [])
        if not values:
            return None
        if vr == "PN":
            first = values[0]
            if isinstance(first, dict):
                return first.get("Alphabetic") or first.get("Ideographic") or first.get("Phonetic")
            return str(first)
        if vr in _STRING_VRS:
            if field_name == "ModalitiesInStudy":
                return [str(v) for v in values]
            return str(values[0])
        if vr in _NUMERIC_VRS:
            first = values[0]
            try:
                return int(first) if vr in {"IS", "US", "UL", "SS", "SL"} else float(first)
            except (TypeError, ValueError):
                return None
        first = values[0]
        return first if isinstance(first, (str, int, float, bool)) else str(first)

    def _parse_dicom_json(dicom_obj: dict, tag_map: dict) -> dict:
        result = {}
        for tag, field_name in tag_map.items():
            tag_obj = dicom_obj.get(tag.upper()) or dicom_obj.get(tag.lower())
            result[field_name] = _extract_dicom_value(tag_obj, field_name) if tag_obj else None
        return result

    def _parse_study(dicom_obj: dict) -> dict:
        return _parse_dicom_json(dicom_obj, STUDY_TAG_MAP)

    def _parse_series(dicom_obj: dict) -> dict:
        return _parse_dicom_json(dicom_obj, SERIES_TAG_MAP)

    def _parse_instance(dicom_obj: dict) -> dict:
        record = _parse_dicom_json(dicom_obj, INSTANCE_TAG_MAP)
        record.setdefault("dicom_file_path", None)
        return record

    ########################################################
    # sources/dicomweb/dicomweb_schemas.py
    ########################################################

    STUDIES_SCHEMA = StructType([
        StructField("StudyInstanceUID",              StringType(),           nullable=False),
        StructField("PatientID",                     StringType(),           nullable=True),
        StructField("PatientName",                   StringType(),           nullable=True),
        StructField("StudyDate",                     StringType(),           nullable=True),
        StructField("StudyTime",                     StringType(),           nullable=True),
        StructField("AccessionNumber",               StringType(),           nullable=True),
        StructField("StudyDescription",              StringType(),           nullable=True),
        StructField("ModalitiesInStudy",             ArrayType(StringType()), nullable=True),
        StructField("NumberOfStudyRelatedSeries",    IntegerType(),          nullable=True),
        StructField("NumberOfStudyRelatedInstances", IntegerType(),          nullable=True),
    ])

    SERIES_SCHEMA = StructType([
        StructField("SeriesInstanceUID",  StringType(),  nullable=False),
        StructField("StudyInstanceUID",   StringType(),  nullable=True),
        StructField("StudyDate",          StringType(),  nullable=True),
        StructField("SeriesNumber",       IntegerType(), nullable=True),
        StructField("SeriesDescription",  StringType(),  nullable=True),
        StructField("Modality",           StringType(),  nullable=True),
        StructField("BodyPartExamined",   StringType(),  nullable=True),
        StructField("SeriesDate",         StringType(),  nullable=True),
    ])

    INSTANCES_SCHEMA = StructType([
        StructField("SOPInstanceUID",    StringType(),  nullable=False),
        StructField("SeriesInstanceUID", StringType(),  nullable=True),
        StructField("StudyInstanceUID",  StringType(),  nullable=True),
        StructField("SOPClassUID",       StringType(),  nullable=True),
        StructField("InstanceNumber",    IntegerType(), nullable=True),
        StructField("StudyDate",         StringType(),  nullable=True),
        StructField("ContentDate",       StringType(),  nullable=True),
        StructField("ContentTime",       StringType(),  nullable=True),
        StructField("dicom_file_path",   StringType(),  nullable=True),
    ])

    _TABLE_SCHEMAS = {
        "studies":   STUDIES_SCHEMA,
        "series":    SERIES_SCHEMA,
        "instances": INSTANCES_SCHEMA,
    }

    ########################################################
    # sources/dicomweb/dicomweb_client.py
    ########################################################

    _DEFAULT_TIMEOUT = (10, 60)

    class DICOMwebClient:
        def __init__(
            self,
            base_url: str,
            auth_type: str = "none",
            username: str | None = None,
            password: str | None = None,
            token: str | None = None,
            timeout: tuple = _DEFAULT_TIMEOUT,
        ) -> None:
            self.base_url = base_url.rstrip("/")
            self.timeout = timeout
            self._session = requests.Session()
            self._session.headers.update({"Accept": "application/dicom+json"})
            auth_type = (auth_type or "none").lower()
            if auth_type == "basic":
                if not username or not password:
                    raise ValueError("auth_type=basic requires username and password")
                self._session.auth = HTTPBasicAuth(username, password)
            elif auth_type == "bearer":
                if not token:
                    raise ValueError("auth_type=bearer requires token")
                self._session.headers["Authorization"] = f"Bearer {token}"
            elif auth_type != "none":
                raise ValueError(f"Unsupported auth_type '{auth_type}'. Use: none, basic, bearer")

        def _qido_get(self, path: str, params: dict) -> list:
            url = f"{self.base_url}{path}"
            resp = self._session.get(url, params=params, timeout=self.timeout)
            if resp.status_code == 204:
                return []
            resp.raise_for_status()
            if not resp.content:
                return []
            return resp.json()

        def query_studies(self, study_date_range: str, limit: int = 100, offset: int = 0) -> list:
            return self._qido_get("/studies", {"StudyDate": study_date_range, "limit": limit, "offset": offset})

        def query_series(self, study_date_range: str, limit: int = 100, offset: int = 0) -> list:
            return self._qido_get("/series", {"StudyDate": study_date_range, "limit": limit, "offset": offset})

        def query_instances(self, study_date_range: str, limit: int = 100, offset: int = 0) -> list:
            return self._qido_get("/instances", {"StudyDate": study_date_range, "limit": limit, "offset": offset})

        def retrieve_instance(self, study_uid: str, series_uid: str, sop_uid: str) -> bytes:
            url = f"{self.base_url}/studies/{study_uid}/series/{series_uid}/instances/{sop_uid}"
            resp = self._session.get(
                url,
                headers={"Accept": 'multipart/related; type="application/dicom"'},
                timeout=self.timeout,
            )
            resp.raise_for_status()
            content_type = resp.headers.get("Content-Type", "")
            if "multipart/related" in content_type:
                return _extract_first_multipart_part(resp.content, content_type)
            return resp.content

    def _parse_boundary(content_type: str) -> str | None:
        for segment in content_type.split(";"):
            segment = segment.strip()
            if segment.lower().startswith("boundary="):
                return segment[len("boundary="):].strip().strip('"')
        return None

    def _extract_first_multipart_part(body: bytes, content_type: str) -> bytes:
        boundary = _parse_boundary(content_type)
        if not boundary:
            return body
        sep = f"--{boundary}".encode()
        parts = body.split(sep)
        for part in parts[1:]:
            if part.strip() in (b"", b"--", b"--\r\n", b"--\n"):
                continue
            if b"\r\n\r\n" in part:
                return part.split(b"\r\n\r\n", 1)[1].rstrip(b"\r\n")
            if b"\n\n" in part:
                return part.split(b"\n\n", 1)[1].rstrip(b"\n")
            return part
        return body

    ########################################################
    # sources/dicomweb/dicomweb.py
    ########################################################

    _SUPPORTED_TABLES = ("studies", "series", "instances")
    _DEFAULT_START_DATE = "19000101"
    _DEFAULT_PAGE_SIZE = 100
    _DEFAULT_LOOKBACK_DAYS = 1
    _DEFAULT_DOWNLOAD_THREADS = 8

    def _subtract_days(date_str: str, days: int) -> str:
        if date_str == _DEFAULT_START_DATE or days == 0:
            return date_str
        try:
            d = date(int(date_str[:4]), int(date_str[4:6]), int(date_str[6:8]))
            return (d - timedelta(days=days)).strftime("%Y%m%d")
        except (ValueError, IndexError):
            return date_str

    class DICOMwebLakeflowConnect(LakeflowConnect):
        def __init__(self, options: dict[str, str]) -> None:
            super().__init__(options)
            base_url = options.get("base_url")
            if not base_url:
                raise ValueError("Connection option 'base_url' is required")
            self._client = DICOMwebClient(
                base_url=base_url,
                auth_type=options.get("auth_type", "none"),
                username=options.get("username"),
                password=options.get("password"),
                token=options.get("token"),
            )

        def list_tables(self) -> list[str]:
            return list(_SUPPORTED_TABLES)

        def get_table_schema(self, table_name: str, table_options: dict[str, str]) -> StructType:
            if table_name not in _TABLE_SCHEMAS:
                raise ValueError(f"Unknown table '{table_name}'")
            return _TABLE_SCHEMAS[table_name]

        def read_table_metadata(self, table_name: str, table_options: dict[str, str]) -> dict:
            pk_map = {
                "studies":   "StudyInstanceUID",
                "series":    "SeriesInstanceUID",
                "instances": "SOPInstanceUID",
            }
            return {"primary_keys": [pk_map[table_name]], "cursor_field": "StudyDate", "ingestion_type": "cdc"}

        def read_table(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            if table_name not in _SUPPORTED_TABLES:
                raise ValueError(f"Unknown table '{table_name}'")

            start_offset = start_offset or {}
            page_size = int(table_options.get("page_size", _DEFAULT_PAGE_SIZE))
            lookback_days = int(table_options.get("lookback_days", _DEFAULT_LOOKBACK_DAYS))
            date_cursor = start_offset.get("study_date", _DEFAULT_START_DATE)
            page_offset = start_offset.get("page_offset", 0)
            today_str = date.today().strftime("%Y%m%d")
            effective_start = _subtract_days(date_cursor, lookback_days)
            date_range = f"{effective_start}-{today_str}"

            fetch_files = table_options.get("fetch_dicom_files", "false").lower() == "true"
            volume_path = table_options.get("dicom_volume_path", "")
            download_threads = int(table_options.get("download_threads", _DEFAULT_DOWNLOAD_THREADS))
            if fetch_files and not volume_path and table_name == "instances":
                raise ValueError("fetch_dicom_files=true requires dicom_volume_path to be set")

            records_iter = self._paginate(table_name, date_range, page_size, page_offset, fetch_files, volume_path, download_threads)
            next_offset = {"study_date": today_str, "page_offset": 0}
            return records_iter, next_offset

        def _paginate(self, table_name, date_range, page_size, start_offset, fetch_files, volume_path, download_threads):
            query_fn = {"studies": self._client.query_studies, "series": self._client.query_series, "instances": self._client.query_instances}[table_name]
            parse_fn = {"studies": _parse_study, "series": _parse_series, "instances": _parse_instance}[table_name]
            offset = start_offset
            while True:
                raw_records = query_fn(date_range, limit=page_size, offset=offset)
                if not raw_records:
                    break
                records = [parse_fn(raw) for raw in raw_records]
                if fetch_files and table_name == "instances":
                    with ThreadPoolExecutor(max_workers=download_threads) as pool:
                        records = list(pool.map(
                            lambda r: self._attach_dicom_file(r, volume_path),
                            records,
                        ))
                yield from records
                if len(raw_records) < page_size:
                    break
                offset += page_size

        def _attach_dicom_file(self, record: dict, volume_path: str) -> dict:
            study_uid = record.get("StudyInstanceUID")
            series_uid = record.get("SeriesInstanceUID")
            sop_uid = record.get("SOPInstanceUID")
            if not all([study_uid, series_uid, sop_uid]):
                return record
            dest_path = pathlib.Path(volume_path) / study_uid / series_uid / f"{sop_uid}.dcm"
            try:
                dicom_bytes = self._client.retrieve_instance(study_uid, series_uid, sop_uid)
                try:
                    dest_path.parent.mkdir(parents=True, exist_ok=True)
                except OSError:
                    # UC Volume FUSE mounts do not support mkdir via POSIX syscalls;
                    # the write_bytes() call below works regardless.
                    pass
                dest_path.write_bytes(dicom_bytes)
                record["dicom_file_path"] = str(dest_path)
            except Exception as exc:
                logging.getLogger(__name__).error("WADO-RS retrieval failed for %s: %s", sop_uid, exc)
                record["dicom_file_path"] = None
            return record

    ########################################################
    # src/databricks/labs/community_connector/sparkpds/lakeflow_datasource.py
    ########################################################

    LakeflowConnectImpl = DICOMwebLakeflowConnect
    METADATA_TABLE = "_lakeflow_metadata"
    TABLE_NAME = "tableName"
    TABLE_NAME_LIST = "tableNameList"
    TABLE_CONFIGS = "tableConfigs"
    IS_DELETE_FLOW = "isDeleteFlow"

    class LakeflowStreamReader(SimpleDataSourceStreamReader):
        def __init__(self, options, schema, lakeflow_connect):
            self.options = options
            self.lakeflow_connect = lakeflow_connect
            self.schema = schema

        def initialOffset(self):
            return {}

        def read(self, start: dict) -> tuple:
            is_delete_flow = self.options.get(IS_DELETE_FLOW) == "true"
            table_options = {k: v for k, v in self.options.items() if k != IS_DELETE_FLOW}
            if is_delete_flow:
                records, offset = self.lakeflow_connect.read_table_deletes(self.options[TABLE_NAME], start, table_options)
            else:
                records, offset = self.lakeflow_connect.read_table(self.options[TABLE_NAME], start, table_options)
            rows = map(lambda x: parse_value(x, self.schema), records)
            return rows, offset

        def readBetweenOffsets(self, start: dict, end: dict) -> Iterator:
            return self.read(start)[0]

    class LakeflowBatchReader(DataSourceReader):
        def __init__(self, options, schema, lakeflow_connect):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]

        def read(self, partition):
            if self.table_name == METADATA_TABLE:
                all_records = self._read_table_metadata()
            else:
                all_records, _ = self.lakeflow_connect.read_table(self.table_name, None, self.options)
            return iter(map(lambda x: parse_value(x, self.schema), all_records))

        def _read_table_metadata(self):
            table_names = [o.strip() for o in self.options.get(TABLE_NAME_LIST, "").split(",") if o.strip()]
            table_configs = json.loads(self.options.get(TABLE_CONFIGS, "{}"))
            return [
                {TABLE_NAME: t, **self.lakeflow_connect.read_table_metadata(t, table_configs.get(t, {}))}
                for t in table_names
            ]

    class LakeflowSource(DataSource):
        def __init__(self, options):
            self.options = options
            self.lakeflow_connect = LakeflowConnectImpl(options)

        @classmethod
        def name(cls):
            return "lakeflow_connect"

        def schema(self):
            table = self.options[TABLE_NAME]
            if table == METADATA_TABLE:
                return StructType([
                    StructField(TABLE_NAME,      StringType(),            False),
                    StructField("primary_keys",  ArrayType(StringType()), True),
                    StructField("cursor_field",  StringType(),            True),
                    StructField("ingestion_type", StringType(),           True),
                ])
            return self.lakeflow_connect.get_table_schema(table, self.options)

        def reader(self, schema: StructType):
            return LakeflowBatchReader(self.options, schema, self.lakeflow_connect)

        def simpleStreamReader(self, schema: StructType):
            return LakeflowStreamReader(self.options, schema, self.lakeflow_connect)

    spark.dataSource.register(LakeflowSource)
